name: Sync README to Pages Repo

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Push to GitHub Pages repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/mondial7/mondial7.github.io.git site
          cp README.md site/index.md
          cd site
          git add index.md
          git commit -m "Update from profile README" || echo "No changes"
          git push
